image: Visual Studio 2017

clone_script:
- ps: >-
    if(-not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
      git clone -q --branch=$env:APPVEYOR_REPO_BRANCH https://github.com/$env:APPVEYOR_REPO_NAME.git $env:APPVEYOR_BUILD_FOLDER
      cd $env:APPVEYOR_BUILD_FOLDER
      git checkout -qf $env:APPVEYOR_REPO_COMMIT
    } else {
      git clone -q https://github.com/$env:APPVEYOR_REPO_NAME.git $env:APPVEYOR_BUILD_FOLDER
      cd $env:APPVEYOR_BUILD_FOLDER
      git fetch -q origin +refs/pull/$env:APPVEYOR_PULL_REQUEST_NUMBER/merge:
      git checkout -qf FETCH_HEAD
    }
- cmd: git submodule update --init --recursive

init:
  - set QTDIR=C:\Qt\5.12\msvc2017_64
  - set PATH=%PATH%;C:\Qt\5.12\msvc2017_64\bin;
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64
build_script:
  - qmake QUsb2snes.pro -spec win32-msvc "CONFIG+=release"
  - nmake
  - lrelease QUsb2Snes.pro
  - qmake WinUpdater.pro -spec win32-msvc "CONFIG+=release"
  - nmake
  - cd QFile2Snes
  - qmake QFile2Snes.pro -spec win32-msvc "CONFIG+=release"
  - nmake
  - lrelease QFile2Snes.pro
  - qmake SendToSd2Snes.pro -spec win32-msvc "CONFIG+=release"
  - lrelease SendToSd2Snes.pro
  - nmake
  - cd ..

after_build:
  - mkdir QUsb2Snes
  - mkdir QUsb2Snes\apps
  - xcopy release\QUsb2Snes.exe QUsb2Snes\
  - xcopy release\WinUpdater.exe QUsb2Snes\
  - cd QUsb2Snes
  - windeployqt.exe --no-translations --no-system-d3d-compiler --no-opengl-sw --no-opengl --no-webkit --no-patchqt --no-webkit2 --release  QUsb2Snes.exe
  - del libEGL.dll
  - del libGLESV2.dll
  - del vc_redist.x64.exe
  - copy /y ..\LICENSE LICENCE-GPLV3.txt
  - copy /y ..\README.md Readme.txt
  - mkdir LuaBridge
  - copy ..\LuaBridge\luabridge.lua LuaBridge\
  - cd LuaBridge\
  - appveyor DownloadFile http://www.nyo.fr/~skarsnik/socket.dll -FileName socket.dll
  - cd ..
  # Translations
  - mkdir i18n
  - xcopy /y ..\Translations\qusb2snes_fr.qm i18n\
  - cd ..
  # QFile2Snes deployment
  - copy QFile2Snes\release\SendToSd2Snes.exe QUsb2Snes\
  - mkdir QUsb2Snes\apps\QFile2Snes
  - xcopy QFile2Snes\release\QFile2Snes.exe QUsb2Snes\apps\QFile2Snes\
  - copy QFile2Snes\icon50x50.png QUsb2Snes\apps\QFile2Snes\icone.png
  - xcopy QFile2Snes\qusb2snesapp.json QUsb2Snes\apps\QFile2Snes\
  # Translations
  - mkdir QUsb2Snes\apps\QFile2Snes\i18n
  - xcopy QFile2Snes\Translations\qfile2snes_fr.qm QUsb2Snes\apps\QFile2Snes\i18n\
  - xcopy QFile2Snes\Translations\sendtodialog_fr.qm QUsb2Snes\i18n\
  - appveyor DownloadFile https://github.com/Skarsnik/snesclassicstuff/releases/download/serverstuffmod_v1/serverstuff.hmod -FileName serverstuff.hmod
  - copy serverstuff.hmod QUsb2Snes\
  # Open SSL for the updater
  - copy C:\OpenSSL-Win64\bin\libeay32.dll QUsb2Snes\libeay32.dll
  - copy C:\OpenSSL-Win64\bin\ssleay32.dll QUsb2Snes\ssleay32.dll
  - 7z a QUsb2Snes-%APPVEYOR_REPO_TAG_NAME%.7z QUsb2Snes


artifacts:
  - path: QUsb2Snes-$(APPVEYOR_REPO_TAG_NAME).7z
    name: package
  - path: release\QUsb2Snes.exe
    name: executable
  - path: QFile2Snes\release\QFile2Snes.exe
    name: qfile2snes
  - path: release\WinUpdater.exe
    name: winupdater

deploy:
  description: 'Automated deployment'
  provider: GitHub
  auth_token:
    secure: JF5Ki0Bz+mvMrqw5k0u7273c8GsUAqMwe/P7ts5PKLR+G7InkGqkvTqlAZb6GDGv
  artifact: release\QUsb2Snes.exe, QFile2Snes\release\QFile2Snes.exe, release\WinUpdater.exe, QUsb2Snes-$(APPVEYOR_REPO_TAG_NAME).7z
  draft: true
  prerelease: false
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true
