This document will guide you through the compiling process. QUsb2Snes can be built with Qt 5.8 minimum but
we recommend using Qt 6.5 or higher.

== Submodules

If you get the source code with a `git clone`, you need to set up the git submodules.

[source, bash]
----
git submodule init
git submodule update
----

== Linux

=== Prerequisites

* You need the development files for Qt
* You will need the development files for websocket and serialport libraries that goes with your Qt version
* You can either use the Qbs build tool or the regular qmake build too to build it. QMake is simpler to use.

=== Compiling the GUI version (default)

[source,bash]
----
qmake QUsb2snes.pro CONFIG+='release'
make
----

Then, start the QUsb2Snes binary directory that is created.

=== Compiling without GUI

If you want to build a version that does not use a Gui (to use it without a XServer):

[source,bash]
----
qmake "QUSB2SNES_NOGUI=1" CONFIG+='release'
make
----

=== Compiling for installing

QUsb2snes will compile by default in a standalone mode where the config file is set on its current directory.
You need to use the `sqpackager_unix_installer.sh` script that will set all the proper things and install all the related files
like the localizations, desktop and man according to the specified prefix
[source,bash]
----
sh ./sqpackager_unix_installer.sh --build --install --prefix /usr/local/
----

If you need to specify which qmake version to use you can use the `--qmake-cmd` argument

== Windows

* Install Qt 6 
* Open the `.qbs` file with QCreator

== MacOS

=== Prerequisites

* Install Homebrew
* Install Qt 5

[source,bash]
----
brew install qt5
brew link qt5 --force
----

* retrieve the submodules

[source,bash]
----
git submodule update --init
----

