.TH QFile2Snes 1 "18 Jun 2024" "version v0.7.28-2-g8bccb22"

.\" The name of the executable
.SH NAME
QFile2Snes - This software allow you to access your FxPak Pro files and more

.\" This is how you start your program and if there is any additional option
.SH SYNOPSIS

QFile2Snes

.\" The complete description
.SH DESCRIPTION
QFile2Snes allow you to access your FxPak Pro files, uploading new Rom and booting them. You need a software like QU2Snes or SNI to be able to use it

.\" Auhtor infos
.SH AUTHOR
Sylvain Colinet <scolinet@gmail.com>
